### ISSUE TITLE
Reduce space between items in the colum "description"

### ISSUE THREAD

**Issue by arpm92** [USi-IPEM/CIRP_CMS21#3]
https://github.com/USi-IPEM/CIRP_CMS21/blob/34ace8937b5f6690af0a908d37c0feddbaef5052/02_Paper/paper.tex#L353

Do you have any idea how to reduce the space between items? Prof Garcke pointed the big space out, and it would be nice to reduce it.

Thank you!

**Comment by v0lta** [comment]
I replaced the description environment with 0.1cm vspaces. In my opinion, it looks better now.
